### ISSUE TITLE
API translation to OrbitDB

### ISSUE THREAD

**Issue by flavioaiello** [rancher/kine#55]
Hi Folks, 

I wonder if anyone has already considered doing the API translation to [orbitdb](https://github.com/berty/go-orbit-db).  Maybe a closer project maintainer can answer this in short. Thanks 

Cheers, Flavio

**Comment by brandond** [comment]
We don't currently have any plans to add additional backends. I see that OrbitDB is eventually consistent - this would not be a good fit for Kubernetes, as it has some strong expectations around atomicity and consistency.

**Comment by flavioaiello** [comment]
Thank you for feedback. The proposal for eventually consistency was intended for a massive scale out of k3s. Just as an idea...
