### ISSUE TITLE
DynamoDB backend

### ISSUE THREAD

**Issue by captn3m0** [rancher/kine#59]
Want to see if this might be considered, seeing as how there was some prior discussion on this: https://github.com/kubernetes/kubernetes/issues/53162, https://github.com/etcd-io/etcd/issues/10321

**Comment by brandond** [comment]
Kine in built on top of a SQL datastore, while DynamoDB is a key-value store. It would be interesting to try to build an etcd layer for DynamoDB, but I don't think kine is the best place to do that since it relies on a sql backend.

**Comment by captn3m0** [comment]
Thanks a lot, closing this.

**Comment by captn3m0** [comment]
Interesting development: DynamoDB now supports (limited) SQL. Only in some regions as of now.

https://aws.amazon.com/about-aws/whats-new/2020/11/you-now-can-use-a-sql-compatible-query-language-to-query-insert-update-and-delete-table-data-in-amazon-dynamodb/
